version_build: 1.0.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-redis-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-redis-master
  template:
    metadata:
      labels:
        app: app-redis-master
    spec:
      containers:
        - name: app-redis-master
          image: "redis"
          ports:
            - name: api
              containerPort: 6379
---
kind: Service
apiVersion: v1
metadata:
  name: "redis-master"
spec:
  selector:
    app: "app-redis-master"
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: edith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edith
  template:
    metadata:
      labels:
        app: edith
    spec:
      containers:
        - name: edith
          imagePullPolicy: Always
          image: "eu.gcr.io/edith-259213/edith:1.0.0"
          ports:
            - name: http
              containerPort: 8080
      initContainers:
        - name: init-redis-master
          image: busybox
          command: ['sh', '-c', 'until nslookup redis-master; do echo waiting for redis-master; sleep 2; done;']
---
kind: Service
apiVersion: v1
metadata:
  name: "edith"
spec:
  type: LoadBalancer
  selector:
    app: "edith"
  ports:
    - port: 8080
